name: My workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.7
        bundler-cache: true

    - run: |
      git clone https://github.com/CocoaPods/Humus.git
      cd Humus
      bundle install
      RACK_ENV=test bundle exec rake db:bootstrap
 
    - run: bundle exec rake

  services:
      postgres:
        image: postgres:9.4
        env:
          POSTGRES_PASSWORD: ""
